# Makefile for Django Hackathon Project

run:
	python manage.py runserver

migrate:
	python manage.py migrate

makemigrations:
	python manage.py makemigrations

createsuperuser:
	python manage.py createsuperuser

shell:
	python manage.py shell

clean:
	find . -name '*.pyc' -delete

	# Makefile for Django Hackathon Project

# Define the path to your Python virtual environment
# VENV = venv
# ACTIVATE = source $(VENV)/bin/activate

# run:
# 	$(ACTIVATE) && \
# 	python manage.py makemigrations && \
# 	python manage.py migrate && \
# 	python manage.py runserver

# # If you want separate commands for devs:
# migrate:
# 	$(ACTIVATE) && python manage.py migrate

# makemigrations:
# 	$(ACTIVATE) && python manage.py makemigrations

# createsuperuser:
# 	$(ACTIVATE) && python manage.py createsuperuser

# shell:
# 	$(ACTIVATE) && python manage.py shell

